# https://github.com/elastic/kibana-docker
ARG elk_version
#FROM docker.elastic.co/kibana/kibana-oss:${elk_version}
FROM docker.elastic.co/kibana/kibana:${elk_version}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
# RUN kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-6.7.1-0.1.31.zip
