# https://github.com/elastic/elasticsearch-docker
ARG elk_version
#FROM docker.elastic.co/elasticsearch/elasticsearch-oss:${elk_version}
FROM docker.elastic.co/elasticsearch/elasticsearch:${elk_version}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
