# https://github.com/elastic/elasticsearch-docker
ARG elk_version
FROM docker.elastic.co/apm/apm-server-oss:${elk_version}
#FROM docker.elastic.co/apm/apm-server:${elk_version}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
