# https://github.com/elastic/logstash-docker
ARG elk_version
#FROM docker.elastic.co/logstash/logstash-oss:${elk_version}
FROM docker.elastic.co/logstash/logstash:${elk_version}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
